name: PHP - Checks

on:
    #push:
    pull_request:
    #schedule:
    #    -   cron:  '0 3 * * *'

jobs:
    checks:
        runs-on: ubuntu-latest
        name: PHP-checks
        steps:
            # Setup
            -   uses: actions/checkout@v2

            -   name: '[PHP] Setup'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    extensions: mbstring, intl
                    coverage: xdebug

            # Prepare application
            -   name: '[INIT] Install dependencies'
                run: composer install --no-progress

            # Check application
            -   name: '[CHECK] codestyle'
                run: composer analyze

            -   name: '[CHECK] phpstan - src'
                run: composer phpstan

            -   name: '[CHECK] Unit tests'
                run: composer test-ci

            -   name: Submit coverage to Coveralls
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    COVERALLS_PARALLEL: true
                    COVERALLS_FLAG_NAME: ${{ github.job }}-PHP-7.3
                run: |
                    composer global require php-coveralls/php-coveralls
                    ~/.composer/vendor/bin/php-coveralls --coverage_clover=./code-coverage/clover.xml --json_path=./code-coverage/coveralls-upload.json -v

    finish-tests:
        name: Tests finished
        needs: [ checks ]
        runs-on: ubuntu-latest
        steps:
            -   name: Notify Coveralls
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    parallel-finished: true
